name: CI_RAFT

# We run CI on push commits and pull requests on all branches
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build_conda:
        name: Conda Build (${{ matrix.os }}) - ${{ matrix.python-version }}
        runs-on: ${{ matrix.os }}
        defaults:
            run:
                shell: bash -l {0}
                
        strategy:
            fail-fast: false #true
            matrix:
                os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
                python-version: ["3.10", "3.11"]

        steps:
            - name: checkout repository
              uses: actions/checkout@v3

            - uses: conda-incubator/setup-miniconda@v2
              # https://github.com/marketplace/actions/setup-miniconda
              with:
                  mamba-version: "*"
                  miniconda-version: "latest"
                  #auto-update-conda: true
                  python-version: ${{ matrix.python-version }}
                  environment-file: environment.yml
                  channels: conda-forge
                  channel-priority: true          
                  activate-environment: test
                  auto-activate-base: false

            # Install 
            - name: Conda Install RAFT
              run: |
                  pip install -e .

            - name: Example run
              run: |
                  cd examples
                  python example_from_yaml.py false

            - name: Test run
              run: |
                  cd tests
                  pytest .

